platform :ios, '7.0'
#use_frameworks!

target 'CJPopupActionDemo' do
    pod 'CJBaseUIKit/CJScrollView', '~> 0.0.5'
    
    pod 'CJPopupAction',       :path => '../'
end

target 'CJPopupActionDemoTests' do
    
end
